# Assignment 6
**UCS420 – Cognitive Computing**

**NumPy – II**

**Name:** Sumit Bansal  
**Roll No:** 1024170041

In [1]:
import numpy as np

## Q.1
Consider the following sensor readings:

`temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])`

A sensor has an average measurement error of +2°C. Perform the following **without using a for loop**:

a. Add 2°C to every reading using vectorization.  
b. Convert all temperatures from Celsius to Fahrenheit using F = (9/5)C + 32.  
c. Identify all readings greater than 32°C using Boolean indexing.  
d. Count how many readings exceed 32°C.  
e. Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value.

In [2]:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
print("Original readings:", temperature)

Original readings: [25 28 31 35 38 27 33 40]


In [3]:
# a) Add 2 °C to every reading (vectorized)
adjusted = temperature + 2
print("a) After adding 2°C        :", adjusted)

a) After adding 2°C        : [27 30 33 37 40 29 35 42]


In [4]:
# b) Celsius -> Fahrenheit
fahrenheit = (9/5) * temperature + 32
print("b) Temperatures in °F      :", fahrenheit)

b) Temperatures in °F      : [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]


In [5]:
# c) Boolean indexing: readings > 32°C
mask = temperature > 32
print("Boolean mask               :", mask)
print("c) Readings greater than 32:", temperature[mask])

Boolean mask               : [False False False  True  True False  True  True]
c) Readings greater than 32: [35 38 33 40]


In [6]:
# d) Count of readings above 32°C
count = np.sum(temperature > 32)
print("d) Number of readings > 32°C:", count)

d) Number of readings > 32°C: 4


## Q.2
The following matrix represents the number of daily steps recorded by four users over three days:

```python
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]])
```

a. Calculate the total steps recorded.  
b. Calculate the mean number of steps.  
c. Find the maximum and minimum values.  
d. Calculate the total steps for each day using `axis=0`.  
e. Calculate the total steps for each user using `axis=1`.  
f. Find the user/day position containing the maximum number of steps using `argmax()`.

In [7]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]])
print(steps)

[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]


In [8]:
print("a) Total steps          :", np.sum(steps))
print("b) Mean steps           :", np.mean(steps))
print("c) Maximum              :", np.max(steps))
print("   Minimum              :", np.min(steps))

a) Total steps          : 84200
b) Mean steps           : 7016.666666666667
c) Maximum              : 9500
   Minimum              : 4500


In [9]:
# d) Total steps for each day (sum down the rows -> one value per column)
print("d) Total per day  (axis=0):", np.sum(steps, axis=0))

# e) Total steps for each user (sum across the columns -> one value per row)
print("e) Total per user (axis=1):", np.sum(steps, axis=1))

d) Total per day  (axis=0): [26500 27300 30400]
e) Total per user (axis=1): [18300 24500 14400 27000]


In [10]:
# f) Position of the maximum value
flat_index = np.argmax(steps)
user, day = np.unravel_index(flat_index, steps.shape)
print("f) Flat index from argmax():", flat_index)
print(f"   Position (row, col)     : ({user}, {day})")
print(f"   -> User {user + 1}, Day {day + 1} with {steps[user, day]} steps")

f) Flat index from argmax(): 11
   Position (row, col)     : (3, 2)
   -> User 4, Day 3 with 9500 steps


## Q.3
Write a Python program using NumPy to perform the following operations:

a. Create the array `original = np.array([1, 2, 3, 4, 5, 6])`.  
b. Create a slice containing elements from index 1 to 4 and store it in `subset`.  
c. Modify the first element of `subset` to 999 and display both `original` and `subset`.  
d. Create another slice from `original` using `.copy()`. Modify its first element to 500 and display `original` and the copied array.  
e. Create an array of numbers 1 to 12 using `np.arange()` and reshape it into a 3 × 4 matrix.  
f. From the 3 × 4 matrix, extract: first row, last row, second column, and elements from rows 1–2 and columns 2–3.  
g. Create a flattened version of the matrix using both `flatten()` and `ravel()`.  
h. Modify an element in the array returned by `ravel()` and observe whether the original is affected.  
i. Modify an element in the array returned by `flatten()` and observe whether the original is affected.  
j. Display the shape, ndim, size and dtype of the original 3 × 4 matrix.

In [11]:
# a) Create the array
original = np.array([1, 2, 3, 4, 5, 6])
print("original:", original)

original: [1 2 3 4 5 6]


In [12]:
# b) Slice from index 1 to 4 (indices 1, 2, 3 -> end index is exclusive)
subset = original[1:4]
print("subset  :", subset)

subset  : [2 3 4]


In [13]:
# c) Modify subset[0] -> slice is a VIEW, so original changes too
subset[0] = 999
print("original:", original)
print("subset  :", subset)

original: [  1 999   3   4   5   6]
subset  : [999   3   4]


In [14]:
# d) Slice with .copy() -> independent array
copied = original[1:4].copy()
copied[0] = 500
print("original:", original)
print("copied  :", copied)

original: [  1 999   3   4   5   6]
copied  : [500   3   4]


In [15]:
# e) arange + reshape
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
# f) Indexing and slicing
print("First row            :", matrix[0])
print("Last row             :", matrix[-1])
print("Second column        :", matrix[:, 1])
print("Rows 1-2, cols 2-3   :\n", matrix[0:2, 1:3])

First row            : [1 2 3 4]
Last row             : [ 9 10 11 12]
Second column        : [ 2  6 10]
Rows 1-2, cols 2-3   :
 [[2 3]
 [6 7]]


In [17]:
# g) flatten() and ravel()
flat = matrix.flatten()
rav = matrix.ravel()
print("flatten():", flat)
print("ravel()  :", rav)

flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel()  : [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [18]:
# h) Modify ravel() result -> original affected?
rav[0] = 100
print("ravel array :", rav)
print("matrix after modifying ravel():\n", matrix)

ravel array : [100   2   3   4   5   6   7   8   9  10  11  12]
matrix after modifying ravel():
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [19]:
# i) Modify flatten() result -> original affected?
flat[1] = 200
print("flatten array:", flat)
print("matrix after modifying flatten():\n", matrix)

flatten array: [  1 200   3   4   5   6   7   8   9  10  11  12]
matrix after modifying flatten():
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [20]:
# j) Attributes of the 3 x 4 matrix
print("Shape:", matrix.shape)
print("ndim :", matrix.ndim)
print("size :", matrix.size)
print("dtype:", matrix.dtype)

Shape: (3, 4)
ndim : 2
size : 12
dtype: int64


## Q.4
A simple cognitive-assistive system wants to predict a user's assistance score based on three factors: **sleep hours**, **activity level** and **stress level**.

```python
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])
```

Each row is one user and each column is a feature.

a. Display the shape and dimensions of X.  
b. Calculate `X.T` and explain what the transpose represents.  
c. Calculate the matrix product `X.T @ X`.  
d. Calculate the matrix inverse using `np.linalg.inv()` where appropriate.  
e. Implement the Ordinary Least Squares equation β = (XᵀX)⁻¹Xᵀy using NumPy.  
f. Explain what the resulting coefficients represent in the context of the three user features.  
g. For `new_user = np.array([5, 40, 7])`, use the calculated coefficients to predict the assistance score.

In [21]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])

# a) Shape and dimensions
print("Shape of X     :", X.shape)
print("Dimensions (ndim):", X.ndim)

Shape of X     : (4, 3)
Dimensions (ndim): 2


In [22]:
# b) Transpose
print("X.T =\n", X.T)
print("Shape of X.T:", X.T.shape)

X.T =
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
Shape of X.T: (3, 4)


In [23]:
# c) Matrix product X.T @ X  (3x4 @ 4x3 -> 3x3)
XtX = X.T @ X
print("X.T @ X =\n", XtX)
print("Shape:", XtX.shape)

X.T @ X =
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Shape: (3, 3)


In [24]:
# d) Inverse of X.T @ X  (a square matrix, so the inverse is valid if det != 0)
print("Determinant of X.T @ X:", np.linalg.det(XtX))
XtX_inv = np.linalg.inv(XtX)
print("(X.T @ X)^-1 =\n", XtX_inv)

# Check: matrix times its inverse should give the identity matrix
print("\nCheck (X.T @ X) @ inverse ≈ I:\n", np.round(XtX @ XtX_inv, 6))

Determinant of X.T @ X: 753700.000000011
(X.T @ X)^-1 =
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

Check (X.T @ X) @ inverse ≈ I:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [25]:
# e) Ordinary Least Squares: beta = (X^T X)^-1 X^T y
beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("OLS coefficients (beta):", beta)
print()
print("Sleep hours    :", round(beta[0], 4))
print("Activity level :", round(beta[1], 4))
print("Stress level   :", round(beta[2], 4))

OLS coefficients (beta): [-0.15921454  0.14083853 10.06302242]

Sleep hours    : -0.1592
Activity level : 0.1408
Stress level   : 10.063


In [26]:
# g) Predict for a new user
new_user = np.array([5, 40, 7])
prediction = new_user @ beta
print("New user features :", new_user)
print("Predicted assistance score:", round(prediction, 2))

New user features : [ 5 40  7]
Predicted assistance score: 75.28
