# Assignment-5
**UCS420 – Cognitive Computing**

**NumPy – Introduction 1**

**Name:** Sumit Bansal  
**Roll No:** 1024170041

In [1]:
import numpy as np

## Q.1
Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:

a) Addition of 2 in all the elements  
b) Multiply 3 with all the elements  
c) Divide every element by 2

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print("Original array        :", arr)
print("a) Add 2 to all       :", arr + 2)
print("b) Multiply by 3      :", arr * 3)
print("c) Divide by 2        :", arr / 2)

Original array        : [10 20 30 40 50]
a) Add 2 to all       : [12 22 32 42 52]
b) Multiply by 3      : [ 30  60  90 120 150]
c) Divide by 2        : [ 5. 10. 15. 20. 25.]


## Q.2
Questions on Basic NumPy Array:

**a)** Reverse the NumPy array: `arr = np.array([1, 2, 3, 6, 4, 5])`

In [3]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original :", arr)
print("Reversed :", arr[::-1])

Original : [1 2 3 6 4 5]
Reversed : [5 4 6 3 2 1]


**b)** Find the most frequent value and their index(es) in the following arrays:

i. `x = np.array([1,2,3,4,5,1,2,1,1,1])`  
ii. `y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])`

In [4]:
def most_frequent(a):
    values, counts = np.unique(a, return_counts=True)
    val = values[np.argmax(counts)]
    idx = np.where(a == val)[0]
    return val, idx

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

for name, a in (("x", x), ("y", y)):
    v, i = most_frequent(a)
    print(f"Array {name} = {a}")
    print(f"  Most frequent value : {v}")
    print(f"  Index(es)           : {i}\n")

# Note: in y, the values 1 and 3 both occur 3 times (a tie); np.argmax picks the first one (1).
vals, cnts = np.unique(y, return_counts=True)
print("Tie check for y ->", dict(zip(vals, cnts)))
print("All values with max count in y:", vals[cnts == cnts.max()])
for v in vals[cnts == cnts.max()]:
    print(f"  Indices of {v}:", np.where(y == v)[0])

Array x = [1 2 3 4 5 1 2 1 1 1]
  Most frequent value : 1
  Index(es)           : [0 5 7 8 9]

Array y = [1 1 1 2 3 4 2 4 3 3]
  Most frequent value : 1
  Index(es)           : [0 1 2]

Tie check for y -> {np.int64(1): np.int64(3), np.int64(2): np.int64(2), np.int64(3): np.int64(3), np.int64(4): np.int64(2)}
All values with max count in y: [1 3]
  Indices of 1: [0 1 2]
  Indices of 3: [4 8 9]


## Q.3
For the given 2-D array `arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`, access elements using row and column indices:

a) Access 1st row, 2nd column  
b) Access 3rd row, 1st column

*(Note: the brackets in the question were missing; a 2-D array needs an outer `[ ]`.)*

In [5]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(arr)
print("a) 1st row, 2nd column :", arr[0, 1])
print("b) 3rd row, 1st column :", arr[2, 0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
a) 1st row, 2nd column : 20
b) 3rd row, 1st column : 70


## Q.4
Write a program to create a 1-D NumPy array named `sumit_bansal` with evenly spaced 25 numbers from 10 to 100 using `linspace()`. Print the dimensions, shape, total elements, data type of each element and total number of bytes consumed by the array. Find the transpose of this array using `reshape()`. Can we do the same with the `T` attribute?

In [6]:
sumit_bansal = np.linspace(10, 100, 25)

print("Array            :", sumit_bansal)
print("Dimensions (ndim):", sumit_bansal.ndim)
print("Shape            :", sumit_bansal.shape)
print("Total elements   :", sumit_bansal.size)
print("Data type        :", sumit_bansal.dtype)
print("Total bytes      :", sumit_bansal.nbytes)

Array            : [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions (ndim): 1
Shape            : (25,)
Total elements   : 25
Data type        : float64
Total bytes      : 200


In [7]:
# Transpose using reshape(): 1-D (25,) -> column vector (25, 1)
transposed = sumit_bansal.reshape(25, 1)
print("Shape after reshape(25, 1):", transposed.shape)
print(transposed)

Shape after reshape(25, 1): (25, 1)
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [8]:
# Using the T attribute on the 1-D array
print("Shape of sumit_bansal.T :", sumit_bansal.T.shape)
print("Same as original?    :", np.array_equal(sumit_bansal.T, sumit_bansal))

# T works only if the array is first made 2-D:
print("Shape of sumit_bansal.reshape(1, 25).T :", sumit_bansal.reshape(1, 25).T.shape)

Shape of sumit_bansal.T : (25,)
Same as original?    : True
Shape of sumit_bansal.reshape(1, 25).T : (25, 1)


**Answer:** No. A 1-D array has only one axis, so the `T` attribute returns the same array unchanged (shape stays `(25,)`). To get a real transpose (column vector), the array must first be 2-D, e.g. `reshape(1, 25).T`, or use `reshape(25, 1)` directly.

## Q.5
Create a 2-D array of three rows and four columns, named `ucs420_<sumit_bansal>` with the values 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it `reshaped_ucs420_<sumit_bansal>`. Resize the array to two rows and three columns and name it `resized_ucs420_<sumit_bansal>`.

In [9]:
ucs420_sumit_bansal = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35]).reshape(3, 4)
print("ucs420_sumit_bansal:\n", ucs420_sumit_bansal)
print()
print("Mean            :", np.mean(ucs420_sumit_bansal))
print("Median          :", np.median(ucs420_sumit_bansal))
print("Max             :", np.max(ucs420_sumit_bansal))
print("Min             :", np.min(ucs420_sumit_bansal))
print("Unique elements :", np.unique(ucs420_sumit_bansal))

ucs420_sumit_bansal:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean            : 43.333333333333336
Median          : 37.5
Max             : 90
Min             : 10
Unique elements : [10 15 20 30 35 40 50 60 70 80 90]


In [10]:
reshaped_ucs420_sumit_bansal = ucs420_sumit_bansal.reshape(4, 3)
print("reshaped_ucs420_sumit_bansal (4x3):\n", reshaped_ucs420_sumit_bansal)

reshaped_ucs420_sumit_bansal (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [11]:
resized_ucs420_sumit_bansal = np.resize(ucs420_sumit_bansal, (2, 3))
print("resized_ucs420_sumit_bansal (2x3):\n", resized_ucs420_sumit_bansal)

resized_ucs420_sumit_bansal (2x3):
 [[10 20 30]
 [40 50 60]]
